### ISSUE TITLE
add posibility to cancel tasks by ids

### ISSUE THREAD

**Issue by hq9000** [sunvalley-technologies/php-task-manager#1]
sometimes, we only know the task's ID which, theoretically, should be enough to identify the task and cancel it. However, we don't have interface for that. the ones we have accept TaskInterface objects.

`    /**
     * Cancel a task. Tasks that are running cannot be canceled.
     *
     * @param TaskInterface $task
     *
     * @return PromiseInterface
     */
    public function cancelTask(TaskInterface $task): PromiseInterface
    {
        return $this->queue->cancelRemote($task);
    }

    /**
     * Cancel a task and wait until the confirmation is done.
     *
     * @param TaskInterface $task
     *
     * @throws \Exception When cancellation is failed
     */
    public function cancelTaskSync(TaskInterface $task)
    {
        await($this->cancelTask($task), $this->queue->getLoop());
    }`

it's needed to add public methods to cancel tasks by ids

**Comment by bmlkc** [comment]
See 

[LeafTask](https://github.com/sunvalley-technologies/php-task-manager/blob/master/src/Task/LeafTask.php)
