### ISSUE TITLE
RedisTaskQueue: make redis keys configurable

### ISSUE THREAD

**Issue by hq9000** [sunvalley-technologies/php-task-manager#2]
currently redis keys are fixed and defined as constangs in RedisTaskQueue class. This makes it impossbile to use the same redis instance for task management purposes of several independent systems.

Needed: to make keys optionally assignable on RedisQueue instantiation.

**Comment by bmlkc** [comment]
It is possible to extend RedisTaskQueue and override those constants.

**Comment by bmlkc** [comment]
closing this, as also a separate redis database can be given with redis uri.
