### ISSUE TITLE
TaskManager\Client should allow returning all progress reporters 

### ISSUE THREAD

**Issue by hq9000** [sunvalley-technologies/php-task-manager#3]
it's needed to be able to get all progress reports of all tasks in the queue:

```
class Client
{
   ...
   // returns a promise that resolves into an array of ProgressReporter instances
   public function checkAllTasksStatus(void): PromiseInterface
   {....}

   ...
   // returns an an array of ProgressReporter instances
   public function checkAllTasksStatusSync(void): array
   {....}

}
```

**Comment by hq9000** [comment]
the PR is coming

**Comment by hq9000** [comment]
a picture to be referenced from the code (putting it here to have it saved)

![image](https://user-images.githubusercontent.com/21345604/86157366-f787d800-bb0f-11ea-940c-2ff01cdcfaa9.png)


illustrates the body of serialized object and a marker substring to be searched for when scanning redis hash with a MATCH parameter

**Comment by bmlkc** [comment]
see #5
